name: tests

on:
  push:
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
        php-parser: ['^1.0', '^2.0', '^3.0', '^4.0', '^5.0']
        exclude:
          - php: 8.0
            php-parser: '^1.0'
          - php: 8.1
            php-parser: '^1.0'
          - php: 8.2
            php-parser: '^1.0'
          - php: 8.3
            php-parser: '^1.0'

          - php: 8.0
            php-parser: '^2.0'
          - php: 8.1
            php-parser: '^2.0'
          - php: 8.2
            php-parser: '^2.0'
          - php: 8.3
            php-parser: '^2.0'

          - php: 8.0
            php-parser: '^3.0'
          - php: 8.1
            php-parser: '^3.0'
          - php: 8.2
            php-parser: '^3.0'
          - php: 8.3
            php-parser: '^3.0'

          - php: 7.2
            php-parser: '^5.0'
          - php: 7.3
            php-parser: '^5.0'

    name: PHP ${{ matrix.php }} | Parser ${{ matrix.php-parser }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update  --prefer-dist --no-interaction --no-progress && composer require nikic/php-parser:${{ matrix.php-parser }}

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
